apiVersion: v1
kind: Pod
metadata:
  name: test-secondary-registry
  namespace: default
spec:
  containers:
  - name: nginx
    image: 127.0.0.1:5001/nginx:alpine
    command: ["sleep", "3600"]
  restartPolicy: Never
