apiVersion: v1
kind: Pod
metadata:
  name: test-unsigned
  labels:
    test: signature-verification
spec:
  containers:
  - name: alpine
    image: 127.0.0.1:5000/alpine:unsigned
    command: ["sh", "-c", "echo 'This should fail!' && sleep 3600"]
  restartPolicy: Never
